//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNDService.Contracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserInfoType", Namespace = "http://schemas.datacontract.org/2004/07/SNDService.Contracts")]
    public partial class UserInfoType : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CardNoField;

        private int CopyTypeField;

        private string DeptIdField;

        private string DeptNameField;

        private int DevNumField;

        private string FeathurePathField;

        private string IPField;

        private string PhotoPathField;

        private string RankIdField;

        private string RankNameField;

        private string TokenField;

        private string UserIdField;

        private string UserNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo
        {
            get
            {
                return this.CardNoField;
            }
            set
            {
                this.CardNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CopyType
        {
            get
            {
                return this.CopyTypeField;
            }
            set
            {
                this.CopyTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptId
        {
            get
            {
                return this.DeptIdField;
            }
            set
            {
                this.DeptIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName
        {
            get
            {
                return this.DeptNameField;
            }
            set
            {
                this.DeptNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DevNum
        {
            get
            {
                return this.DevNumField;
            }
            set
            {
                this.DevNumField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeathurePath
        {
            get
            {
                return this.FeathurePathField;
            }
            set
            {
                this.FeathurePathField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath
        {
            get
            {
                return this.PhotoPathField;
            }
            set
            {
                this.PhotoPathField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankId
        {
            get
            {
                return this.RankIdField;
            }
            set
            {
                this.RankIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IKQHandler")]
public interface IKQHandler
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IKQHandler/InputFeature", ReplyAction = "http://tempuri.org/IKQHandler/InputFeatureResponse")]
    void InputFeature(SNDService.Contracts.UserInfoType userInfo);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IKQHandler/ModifyUser", ReplyAction = "http://tempuri.org/IKQHandler/ModifyUserResponse")]
    int ModifyUser(SNDService.Contracts.UserInfoType userInfo);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IKQHandler/DeleteUser", ReplyAction = "http://tempuri.org/IKQHandler/DeleteUserResponse")]
    int DeleteUser(SNDService.Contracts.UserInfoType userInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IKQHandlerChannel : IKQHandler, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class KQHandlerClient : System.ServiceModel.ClientBase<IKQHandler>, IKQHandler
{

    public KQHandlerClient()
    {
    }

    public KQHandlerClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public KQHandlerClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public KQHandlerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public KQHandlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public void InputFeature(SNDService.Contracts.UserInfoType userInfo)
    {
        base.Channel.InputFeature(userInfo);
    }

    public int ModifyUser(SNDService.Contracts.UserInfoType userInfo)
    {
        return base.Channel.ModifyUser(userInfo);
    }

    public int DeleteUser(SNDService.Contracts.UserInfoType userInfo)
    {
        return base.Channel.DeleteUser(userInfo);
    }
}
